name: Deploy Next.js App (Self Hosted)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Sync code to app directory
        run: |
          rsync -av --delete \
            $GITHUB_WORKSPACE/ \
            /var/www/html/majestic-group/

      - name: Install dependencies
        working-directory: /var/www/html/majestic-group
        run: npm install

      - name: Build Next.js app
        working-directory: /var/www/html/majestic-group
        run: npm run build

      - name: Restart PM2
        working-directory: /var/www/html/majestic-group
        run: |
          pm2 reload nextjs-app || pm2 start npm --name "nextjs-app" -- start
          pm2 save
